on:
  schedule:
    - cron: "26 */2 * * *"
  # push:
  #   branches:
  #     - 'main'

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript, npx, vite-node, gh-pages]

      - name: Run CI
        run: bin/ci.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
